// build.js — runs on Cloudflare Pages before each deploy
// Reads Firebase credentials from environment variables and writes firebase-config.js
// Set these in: Cloudflare Pages → Settings → Environment variables

const fs = require('fs');

const config = {
  apiKey:            process.env.FIREBASE_API_KEY,
  authDomain:        process.env.FIREBASE_AUTH_DOMAIN,
  projectId:         process.env.FIREBASE_PROJECT_ID,
  storageBucket:     process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId:             process.env.FIREBASE_APP_ID,
  measurementId:     process.env.FIREBASE_MEASUREMENT_ID, // optional
};

const required = ['apiKey','authDomain','projectId','storageBucket','messagingSenderId','appId'];
const missing  = required.filter(k => !config[k]);

if (missing.length) {
  console.warn('⚠️  Missing Cloudflare env vars:', missing.join(', '));
  console.warn('   Leaderboard will be disabled on this deploy.');
  // Write a no-op placeholder so the app still loads
  fs.writeFileSync('firebase-config.js',
    '// Firebase not configured — leaderboard disabled\n' +
    'window.FIREBASE_CONFIG = null;\n'
  );
} else {
  fs.writeFileSync('firebase-config.js',
    '// Auto-generated by build.js — do not edit\n' +
    `window.FIREBASE_CONFIG = ${JSON.stringify(config, null, 2)};\n`
  );
  console.log('✅  firebase-config.js written from environment variables.');
}
